name: Build rootfs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: kreato/builder:latest
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
        
      - name: Build rootfs tarball
        run: |
          ln -s $GITHUB_WORKSPACE /nyaa
          mkdir /out
          ln -s /out /nyaa/out
          cd /nyaa
          nyaa u
          sed -i 's/CONFIG_BINARY=n/CONFIG_BINARY=y/g' .config
          sh scripts/build-rootfs.sh
    
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: tarball # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/kreato-linux-*.tar.gz
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error 
