name: Build rootfs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: kreato/builder:latest
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          
      - name: Build rootfs tarball (from source, with custom options)
        run: |
          ln -s $GITHUB_WORKSPACE /nyaa
          mkdir /out
          ln -s /out /nyaa/out
          cd /nyaa
          nyaa u
          echo "CONFIG_BUILDDIR=/out" > .config
          echo "CONFIG_CLIB_GLIBC=y" >> .config
          echo "CONFIG_TLS_OPENSSL=y" >> .config
          echo "CONFIG_CORE_BUSYBOX=y" >> .config
          echo "CONFIG_BINARY=n" >> .config
          sh scripts/build-rootfs.sh
          mv kreato-linux-"$(date +%d-%m-%Y)".tar.gz kreato-linux-nocc-"$(date +%d-%m-%Y)".tar.gz
        
      - name: Build rootfs tarball (from binary, with default options)
        run: |
          rm -rf /out*
          cd /nyaa
          nyaa u
          git restore .config
          sed -i 's/CONFIG_BINARY=n/CONFIG_BINARY=y/g' .config
          sh scripts/build-rootfs.sh
          mv kreato-linux-"$(date +%d-%m-%Y)".tar.gz kreato-linux-builder-"$(date +%d-%m-%Y)".tar.gz
        
    
      - name: Upload Builder Rootfs
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: builder-rootfs # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/kreato-linux-builder-*.tar.gz
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error 

      - name: Upload Source Rootfs
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: nocc-rootfs # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/kreato-linux-nocc-*.tar.gz
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error 
