name: Build rootfs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: kreato/builder:latest
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          
      - name: Build nocc rootfs tarball
        run: |
          ln -s $GITHUB_WORKSPACE /nyaa
          cd /tmp
          wget https://github.com/kreatolinux/nyaa2/archive/refs/tags/v2.1c.tar.gz
          tar -xvf v2.1c.tar.gz
          cd nyaa2-2.1c || exit 1
          mv nyaa "/bin/nyaa"
          chmod +x "/bin/nyaa"
          mkdir /out
          ln -s /out /nyaa/out
          if [ "$(which bsdtar)" = "" ]; then
            echo 'tar "$@"' > /bin/bsdtar
            chmod +x /bin/bsdtar
          fi
          cd /nyaa
          nyaa u
          nyaa b nyaa -y
          sed -i 's/changeme/nocc_defconfig/' scripts/build-rootfs.sh
          sh scripts/build-rootfs.sh
          sed -i 's/nocc_defconfig/changeme/' scripts/build-rootfs.sh
          mv kreato-linux-"$(date +%d-%m-%Y)".tar.gz kreato-linux-nocc-"$(date +%d-%m-%Y)".tar.gz
        
      - name: Build builder rootfs tarball
        run: |
          rm -rf /out*
          cd /nyaa
          git config --global --add safe.directory /__w/nyaastrap/nyaastrap
          nyaa update
          sed -i 's/changeme/builder_defconfig/' scripts/build-rootfs.sh
          sh scripts/build-rootfs.sh
          mv kreato-linux-"$(date +%d-%m-%Y)".tar.gz kreato-linux-builder-"$(date +%d-%m-%Y)".tar.gz
        
    
      - name: Upload Builder Rootfs
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: builder-rootfs # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/kreato-linux-builder-*.tar.gz
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error 

      - name: Upload Source Rootfs
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: nocc-rootfs # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/kreato-linux-nocc-*.tar.gz
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error 
